#!d:\git_folder\mlops-project-with-mlflow\mlenv9.6.24\python.exe
# -*- coding: UTF-8 -*-
from __future__ import print_function, division, absolute_import

from numba.misc.numba_entry import main

if __name__ == "__main__":
    main()
